# get the base image, this one has R, RStudio and pandoc
FROM rocker/tidyverse:3.4.0
# required
MAINTAINER Ian Moran <ian.moran11@gmail.com>

RUN echo "root:root" | chpasswd



# go into the repo directory
RUN   apt-get update 


# To keep on
#sudo docker run --restart=always -d your_image

# to build this image:
# docker build -t ianmoran11/verse_latest /home/ubuntu/dockerfiles/verse_ian

# to run this container:
# docker run  --restart=always -dp 8787:8787 ianmoran11/verse_latest


