# get the base image, this one has R, RStudio and pandoc
FROM rocker/tidyverse:3.4.0
# required
MAINTAINER Ian Moran <ian.moran11@gmail.com>

RUN echo "root:root" | chpasswd



# go into the repo directory
RUN   apt-get update 


RUN R -e "options(repos='https://mran.microsoft.com/snapshot/2017-05-01')"

RUN apt-get update -qq  \ 
  && R -e "source('https://bioconductor.org/biocLite.R')" \
  && install2.r --error \
    --deps FALSE \
    tidyverse \
    dplyr \
    ggplot2 \
    devtools \
    formatR \
    remotes \ 
    broom \
    dplyr \
    ggplot2 \     
    haven  \
    knitr  \
    lubridate \
    purrr \
    readr \
    tidyr \
    stringr \
    tibble \
    foreign \
    dplyr  \
    ggplot2 \
    tidyr  \
    rdrop2  \
    rvest  \
    selectr \
    xml2 \ 
    magrittr 


# To keep on
#sudo docker run --restart=always -d your_image

# to build this image:
# docker build -t ianmoran11/tidyverse_ian_3.4.0 /home/ubuntu/dockerfiles/tidyverse_ian_3.4.0

# to run this container:
# docker run  --restart=always -dp 8787:8787 ianmoran11/tidyverse_ian_3.4.0





