# get the base image, this one has R, RStudio and pandoc
FROM rocker/tidyverse:3.4.0
# required
MAINTAINER Ian Moran <ian.moran11@gmail.com>

RUN echo "root:root" | chpasswd



# go into the repo directory
RUN   apt-get update 

RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" \
      | tee /etc/apt/sources.list.d/webupd8team-java.list \
    &&  echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" \
      | tee -a /etc/apt/sources.list.d/webupd8team-java.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 \
    && echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" \
        | /usr/bin/debconf-set-selections \
    && apt-get update \
    && apt-get install -y oracle-java8-installer \
    && update-alternatives --display java \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && R CMD javareconf

## Install rJava
RUN install2.r --error rJava



RUN  git config --global user.email 'ian.moran11@gmail.com'
RUN  git config --global user.name 'Ian Moran'



# To keep on
#sudo docker run --restart=always -d your_image

# to build this image:
# docker build -t ianmoran11/rjava /home/ubuntu/dockerfiles/rjava

# to run this container:
# docker run  --restart=always -dp 8787:8787 ianmoran11/rjava





