# get the base image, this one has R, RStudio and pandoc
FROM rocker/verse:latest
# required
MAINTAINER Ian Moran <ian.moran11@gmail.com>

## gnupg is needed to add new key
RUN apt-get update && apt-get install -y gnupg2

## Install Java 
RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" \
      | tee /etc/apt/sources.list.d/webupd8team-java.list \
    &&  echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" \
      | tee -a /etc/apt/sources.list.d/webupd8team-java.list \
    && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886 \
    && echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" \
        | /usr/bin/debconf-set-selections \
    && apt-get update \
    && apt-get install -y oracle-java8-installer \
    && update-alternatives --display java \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && R CMD javareconf

## make sure Java can be found in rApache and other daemons not looking in R ldpaths
RUN echo "/usr/lib/jvm/java-8-oracle/jre/lib/amd64/server/" > /etc/ld.so.conf.d/rJava.conf
RUN /sbin/ldconfig

## Install rJava package
RUN install2.r --error rJava \
  && rm -rf /tmp/downloaded_packages/ /tmp/*.rds


RUN echo "root:root" | chpasswd



# go into the repo directory
RUN   apt-get update 


# To keep on
#sudo docker run --restart=always -d your_image

# to build this image:
# docker build -t ianmoran11/verse_ian_rjava /home/ubuntu/dockerfiles/verse_ian_rjava

# to run this container:
# docker run  --restart=always -dp 8787:8787 ianmoran11/verse_ian_rjava


