# get the base image, this one has R, RStudio and pandoc
FROM rocker/tidyverse:3.4.0
# required
MAINTAINER Ian Moran <ian.moran11@gmail.com>

RUN echo "root:root" | chpasswd


RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

# update repos
RUN apt-get update
RUN apt-get install gnupg -y
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys EEA14886

RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee /etc/apt/sources.list.d/webupd8team-java.list
RUN echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list
RUN apt-get update


# install java
RUN apt-get install oracle-java8-installer -y

RUN apt-get clean

#RUN  mkdir -p /usr/lib/jvm/default-java/ && ln -s /usr/lib/jvm/java-8-oracle/ /usr/lib/jvm/default-java/
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle/jre/


# go into the repo directory
RUN   apt-get update 


RUN R -e "options(repos='https://mran.microsoft.com/snapshot/2017-06-07')"

RUN apt-get update -qq  \ 
  && R -e "source('https://bioconductor.org/biocLite.R')" \
  && install2.r \
    --deps TRUE \
    tidyverse \
    devtools \
    formatR \
    remotes \ 
    knitr  \
    lubridate \
    purrr \
    readr \
    tidyr \
    stringr \
    tibble \
    selectr \
    xml2 \ 
    magrittr \
    broom  \
    dplyr \
    haven  \
    ggplot2 \
    aws.s3  \
    pdftools \
    selectr \
    magrittr 

RUN echo "install.packages('rJava', repos='http://www.rforge.net/', configure.args='--disable-Xrs')" | R --no-save

RUN  git config --global user.email 'ian.moran11@gmail.com'
RUN  git config --global user.name 'Ian Moran'



# To keep on
#sudo docker run --restart=always -d your_image

# to build this image:
# docker build -t ianmoran11/tidyverse_ian_20170608 /home/ubuntu/dockerfiles/tidyverse_ian_20170608
# to run this container:
# docker run  --restart=always -dp 8787:8787 ianmoran11/tidyverse_ian_20170608




